# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: repository # name of the parameter; required
  type: string # data type of the parameter; required

stages:
- stage: Docker
  displayName: Build and Push Docker Image
  jobs:
  - job: Build_Push
    displayName: Build and Push Dockerimage
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        # Install buildx
        docker buildx create --use
        docker buildx inspect --bootstrap
  
        # Build and push multi-platform Docker image
        docker buildx build --platform linux/arm64,linux/amd64 -t ghcr.io/viertel97/quantified-self-dashboard:latest -f Dockerfile .
        docker buildx stop
      displayName: 'Build and Push Multi-Platform Docker Image'

    - task: Docker@2
      inputs:
        containerRegistry: 'GHCR'
        repository: 'viertel97/$(parameters.repository)'
        command: 'push'
        tags: 'latest,$(Build.BuildNumber)'
      displayName: 'Push Docker Image'
