name: $(Date:yyyyMMdd)-$(Build.BuildId)

trigger:
- main

resources:
- repo: self

variables:
- group: common

extends:
  template: pipeline-template.yaml
  parameters:
      repository: "quantified-self-dashboard"